### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MyLocalCode**

### CODE REVIEW

**Comment by FriendlyHelper** [comment]
Hi! Thanks for this PR. It is now labeled as "needs-review" for beginning the peer review process.

**Comment by FriendlyHelper** [comment]
Hi! Thanks for this PR. It is now labeled as "needs-review" for beginning the peer review process.

**Comment by FriendlyHelper** [comment]
Hi! Thanks for this PR. It is now labeled as "needs-review" for beginning the peer review process.

**Comment by MyLocalCode** [comment]
LGTM!

**Pull request merged**
